### PR TITLE
Minor fixes, add more attributes from api, add name config

### PR DESCRIPTION
**Pull request by pfiggins**
Fix typos and minor bugs, including the one in #2 
Add attributes, including the ones reported in #1 
Add ability to give a friendly name in the config

(new attributes will require an update to pyinfinitive.py)

### CODE REVIEW

**Comment by bdf0506** [comment]
After installing the new version of pyinfinitve.py as well as this new version of the infinitive climate.py, having an issue.... unless I somehow didn't install pyinfinitive.py the correct way in hass.io. But looking at the pyinfinitive.py code, I see no reference to heatpump_coilTemp, which is what is erroring out.

```
2019-03-09 18:49:29 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform infinitive
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitive/climate.py", line 78, in setup_platform
    add_entities([InfinitiveDevice(inf_device, name, temp_min_spread)])
  File "/config/custom_components/infinitive/climate.py", line 111, in __init__
    self.update()
  File "/config/custom_components/infinitive/climate.py", line 234, in update
    self._heatpump_coil_temp = self._status['heatpump_coilTemp']
KeyError: 'heatpump_coilTemp'
```

**Comment by bdf0506** [comment]
Also an issue with the naming part of the code.

Looks like you can put "friendly name: thermostat" in the configuration.yaml, else it results in the device being created as climate.unnamed_device. While having a friendly name is a nice option, if a friendly name is not put in the code, should support a more ideal name other than "unnamed_device".

**Comment by pfiggins** [comment]
Line 49 in that latest commit  of pyinfinitive is pulling the heat pump values. So it pulls all the json from the heat pump API and adds heatpump_ as a prefix. So coilTemp in the api becomes heatpump_coilTemp. It's working in my local copy. Do you possibly not have a heat pump node on your API? It would be miss.ing if you API didn't expose it...

**Comment by pfiggins** [comment]
You're right. I didn't test without a name. Should probably add a check and default to the original name.

**Comment by bdf0506** [comment]
> Line 49 in that latest commit of pyinfinitive is pulling the heat pump values. So it pulls all the json from the heat pump API and adds heatpump_ as a prefix. So coilTemp in the api becomes heatpump_coilTemp. It's working in my local copy. Do you possibly not have a heat pump node on your API? It would be miss.ing if you API didn't expose it...

Using infinitive, here's the output of the heatpump api call on my end (unit is currently off). I believe everything is exposed that should be exposed.

```
http://192.168.10.10:8080/api/heatpump
{"tempUnit":"F","coilTemp":61.8125,"outsideTemp":64.5625,"stage":0}
```
Based on what I see, it appears that this should simply work, but it's not for some reason. For now to get past the issues, in the climate.py code, I've commented out lines 234-236.

**Comment by pfiggins** [comment]
Man, that is very odd. My API return is similar, as my HVAC is off right now, too. In my testing, I simply dropped the pyinfinitive.py file (as checked in) into /srv/homeassistant/lib/python3.6/site-packages/pyinfinitive on my HA machine and then restarted HA. It sounds like the pyinfinitive.py that is being loaded on your machine is maybe an older version? Maybe you have multiple copies on your HA machine and it's not loading the one you think it is? I know there were multiple ways to run dev versions of a required component, but I chose this as it was the simplest and also would ensure I wouldn't forget to turn it off. The downside being if my PR doesn't get accepted, it would be overwritten on an upgrade.

I just verified again that the file on my HA machine matches what I checked in and the values are being pulled back to my UI.

I added the sensors like so -
```
- platform: template
  sensors:
    hvac_outdoor_temp:
      friendly_name: 'Outdoor Temp'
      value_template: '{{ states.climate.main.attributes.outdoor_temp }}'
      icon_template: mdi:thermometer
    hvac_aux_heat:
      friendly_name: 'Aux Heat'
      value_template: '{{ states.climate.main.attributes.aux_heat }}'
      icon_template: mdi:fire
    hvac_heatpump_coil_temp:
      friendly_name: 'Coil Temp'
      value_template: '{{ states.climate.main.attributes.heatpump_coil_temp }}'
      icon_template: mdi:thermometer
    hvac_heatpump_outside_temp:
      friendly_name: 'Heatpump Outside Temp'
      value_template: '{{ states.climate.main.attributes.heatpump_outside_temp }}'
      icon_template: mdi:thermometer
    hvac_heatpump_stage:
      friendly_name: 'Heatpump Stage'
      value_template: '{{ states.climate.main.attributes.heatpump_stage }}'
    hvac_target_humidity:
      friendly_name: 'Target Humidity'
      value_template: '{{ states.climate.main.attributes.target_humidity }}'
      icon_template: mdi:water-percent     
``` 

And here's what I'm seeing -
image

**Comment by pfiggins** [comment]
Just checked in the default name value so it's not required to be set in the config anymore.

**Comment by pfiggins** [comment]
@bdf0506  I think I may now realize the disconnect. Are you loading the pyinfinitive.py file manually as I explained above or are you expecting it to update to my forked version automatically? The published version is still the version in this main repo, not mine. If @mww012 accepts my PR and releases the update to PyPi, then it would update automatically. Until then, you would need to replace it manually as I explained above or following the instructions here https://developers.home-assistant.io/docs/en/creating_component_deps_and_reqs.html.

**Comment by bdf0506** [comment]
I'm using hass.io, and I'm using the Custom Deps Deployment addon. I've been grabbing the latest version of pyinfinitive.py, letting the add-on install it to /usr/share/hassio/homeassistant/deps/lib/python3.6/site-packages/pyinfinitive/pyinfinitive.py  and off to the races. I now only see the most recent version of that file in Home Assistant under, but perhaps when I am loading the infinitive.py module, it is somehow loading an old one?

**Comment by pfiggins** [comment]
Ah, I've never used hass.io, so I'm not totally sure how that addon works. Are you pulling the pyinfinitive.py file from my forked repo at https://github.com/pfiggins/pyinfinitive? If you pull from this repo (original from mww012), then you won't get my changes since they haven't been accepted yet.

**Comment by bdf0506** [comment]
Yes, I am pulling the new code. I'll have to mess with this a bit further, since it sounds like its more of the pyinfinitive.py is the part that is holding us up here.

**Comment by mww012** [comment]
Hey guys.  Sorry I’m a little late to the conversation. @pfiggins I’ll take a look through this PR today and hopefully get it published.

**Review by mww012 — COMMENTED** [review]
On line 34 your added ‘off’ to the operations list. I originally had that in but could never get it to function. I didn’t want to add in an option I knew wouldn’t work. Does it work for you?

Outside of that the rest of it makes sense to me.

**Comment by pfiggins** [comment]
Sweet, thanks @mww012. Yes, off definitely works for me. I hit the power icon on the UI and the carrier thermostat changes to "system off" and then tap the cool icon in the UI and then it switches back to "hold" at the temperature set. So when you tap the power icon, it just doesn't do anything on your hardware thermostat?

**Comment by mww012** [comment]
Yep.  Just acted like I didn't do anything.  I saw the log come through on the pi zero running infinitive but nothing happened.  Glad it's working for you.

**Comment by mww012** [comment]
Just wanted to let you guys know that I've got both the ha_customcomponent PR and the pyinfinitive PR from @pfiggins merged.  Pyinfinitive has been published to pypi as 0.0.3.  Give it a shot and let me know how it goes.

**Comment by pfiggins** [comment]
Thanks for getting this merged so fast! Just updated it in pip and 0.0.3 is working perfectly. 

For the record, this is the first PR I've even done and I'm a c# guy, too. Had to learn some python, but it was worth it! Thanks for your hard work in putting this together for everyone!

**Comment by mww012** [comment]
Awesome!  This is the first PR request I’ve ever had to do so we’re both in uncharted territory.  I upgraded mine but something’s wrong. I think it’s on my end though. My .homeassistant directory is a git repo and in the middle of this I made the custom_components folder a submodule. I thought it was good but I’m sure a messed up something in there.

**Comment by mww012** [comment]
Found the issue. It wasn’t my git submodule (thank goodness because I don’t know what other solution I could have used). In pyinfinitive.py, on line 41, we commited an f-string so that we could prepend a prefix to k. It’s nice and concise and what I should have done from the start. However, F-strings weren’t implemented until python 3.6. I’m running 3.5.3. I’ll look and see if HA has a compatibility requirement for 3.5. If not I’ll just upgrade.

**Comment by pfiggins** [comment]
Agh. Sorry about that! I'll keep a closer eye on version capabilities in the future. That was the first thing I found on Google when looking for python string formatting.

**Comment by mww012** [comment]
No worries.  I didn't catch it either.  What I'm probably going to end up doing is re-writing that line without the f-string.  I looked at what it was going to take to upgrade to 3.6 and it's basically blowing away the entire 3.5 venv and rebuilding a new one under 3.6.  Given that, I'd like to not force people to upgrade to use this component so I think I'll just do the re-write.

**Pull request merged**
